classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.etcd
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.linux.system.repo.docker
- system.kubernetes.master.cluster
- cluster.k8s_calico.kubernetes.compute
- cluster.k8s_calico
parameters:
  _param:
    keepalived_vip_interface: ens4
    keepalived_vip_virtual_router_id: 60
  etcd:
    server:
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade": true, "cidr": "${_param:calico_private_network}/${_param:calico_private_netmask}"}'
